// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAclhcLpshgRYxql22fnScTK39DIFGzNhY',
    appId: '1:855726156368:web:5c59b9bc9c8bc0fb163f55',
    messagingSenderId: '855726156368',
    projectId: 'boilerplate-e8842',
    authDomain: 'boilerplate-e8842.firebaseapp.com',
    storageBucket: 'boilerplate-e8842.firebasestorage.app',
    measurementId: 'G-JVJFHYXW9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9IQSXHSZ5LtDMcaI-1PCXEF5wINiAJvA',
    appId: '1:855726156368:android:7e04399dcf4643ac163f55',
    messagingSenderId: '855726156368',
    projectId: 'boilerplate-e8842',
    storageBucket: 'boilerplate-e8842.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMgrKH6fzQqt-SieIhl6TLxWZHT3xph04',
    appId: '1:855726156368:ios:074b6571a5a54112163f55',
    messagingSenderId: '855726156368',
    projectId: 'boilerplate-e8842',
    storageBucket: 'boilerplate-e8842.firebasestorage.app',
    androidClientId: '855726156368-1mufe0ujvvorinb2vc74viidrt5r47gk.apps.googleusercontent.com',
    iosClientId: '855726156368-lqbldeqoib6tq8netldjstt319a79njn.apps.googleusercontent.com',
    iosBundleId: 'com.maulana.boilerplate3Firebaseconnect',
  );
}
